export const FETCH_EXCHANGE_RATE_STARTED = 'FETCH_EXCHANGE_RATE_STARTED';
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCESS';
export const FETCH_EXCHANGE_RATE_FAILURE = 'FETCH_EXCHANGE_RATE_FAILURE';